# Generated by Django 2.2.5 on 2020-03-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housework',
            fields=[
                ('housework_id', models.AutoField(primary_key=True, serialize=False)),
                ('housework_name', models.CharField(max_length=100)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workreport',
            fields=[
                ('workreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('rep_date', models.DateField()),
                ('housework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workreport_housework_id', to='house.Housework')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workreport_user_id', to='house.User')),
            ],
            options={
                'ordering': ('-rep_date',),
            },
        ),
        migrations.CreateModel(
            name='Day_rank',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_point', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rank_user_id', to='house.User')),
            ],
            options={
                'ordering': ('-date', '-total_point'),
            },
        ),
    ]
